### ISSUE TITLE
How to use the poise cookbook to add multiple lines to the config file

### ISSUE THREAD

**Issue by AnishAnil** [poise/poise-file#8]
I would like to add the below lines to rsyslog.conf file and would like to know the instruction on how to do this using the poise cookbook

#audit log
$ModLoad imfile
$InputFileName /var/log/audit/audit.log
$InputFileTag tag_audit_log:
$InputFileStateFile audit_log
$InputFileSeverity info
$InputFileFacility local6
$InputRunFileMonitor

Thank you

**Comment by coderanger** [comment]
Same way you were trying with the `line` cookbook (also hi there, you don't need to message me in multiple places). Just set up the regex and pattern mode.

But, again, **DO NOT DO THIS, IT IS BAD AND RSYSLOG SUPPORTS BETTER OPTIONS**.
